sudo: required
services:
  - docker

before_install: 
  - docker build -t 1528280/angular-test -f ./app/Dockerfile.dev ./app
  

script:
  - docker run 1528280/angular-test npm test -- --coverage


after_success: 
  - docker build -t 1528280/multi-app ./app
  - docker build -t 1528280/multi-nginx ./nginx
  - docker build -t 1528280/multi-server ./server
  - docker build -t 1528280/multi-worker ./worker