sudo: required
services:
  - docker

before_install: 
  - docker build -t 1528280/angular-test -f ./app/Dockerfile.dev ./app
  

script:
  - timeout --preserve-status 30s docker run -e CI=true 1528280/angular-test npm run test
  # timeout --preserve-status 30s docker run -e CI=true 1528280/docker-angular npm run test


after_success: 
  - docker build -t 1528280/multi-app ./app
  - docker build -t 1528280/multi-nginx ./nginx
  - docker build -t 1528280/multi-server ./server
  - docker build -t 1528280/multi-worker ./worker
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # TAKE THOSE IMAGES AND PUSH TO DOCKER HUB
  - docker push 1528280/multi-app
  - docker push 1528280/multi-nginx
  - docker push 1528280/multi-server
  - docker push 1528280/multi-worker