FROM node:16-alpine 

WORKDIR "/app"
COPY ./package.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]


#   postgres:
#     image: "postgres:latest"
#     environment:
#       - POSTGRES_PASSWORD=postgres_password